export const content = {
  superbrain: 'SuperBrain®',
  dashboard: 'Dashboard',
  password: 'password',
  email: 'email',
  username: 'username',
  firstname: 'First Name',
  lastname: 'Last Name',
  department: 'department',
  organisation: 'Organisation',
  singin: 'Sign in',
  login: 'Login',
  logout: 'Logout',
  contact_sales: 'Contact Sales',
  tbi: 'TBI',
  email_placeholder: 'latte@trianglehq.co',
  password_placeholder: '*******',
  add_user: 'Add User',
  add_organisation: 'Add Organisation',
  control_panel: 'Control Panel',
  access: 'Access',
  connection: 'Connections',
  analytics: 'Analytics',
  log_reports: 'Log Reports',
  configuration: 'Configuration',
  manage_billing: 'Manage Billing',
  users: 'Users',
  access_key: 'Access Key',
  save_organisation: 'Save Organisation',
  city: 'City',
  state: 'State',
  confirm_password: 'Confirm Password'
}
